###
# Create Post
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "게시글 제목",
  "content": "게시글 내용입니다."
}

###

# Get all posts
GET http://localhost:8080/posts
Accept: application/json


###

# Get posts
GET http://localhost:8080/posts/1
Accept: application/json

###

# Edit Post
PATCH http://localhost:8080/posts/1
Content-Type: application/json

{
  "title": "수정된 제목"
}

###

# Delete posts
DELETE http://localhost:8080/posts/1
Accept: application/json

###



