
###
# Create reply
POST http://localhost:8080/replies
Content-Type: application/json

{
  "title": "댓글 제목",
  "postId": 1,
  "content": "댓글 내용입니다."
}

###

# Get All Replies
GET http://localhost:8080/replies/1
Accept: application/json

###



